### ISSUE TITLE
'Cache Storage' Remains

### ISSUE THREAD

**Issue by wiredrunner** [dessant/clear-browsing-data#24] opened 2019-11-11 16:43 UTC
* OS name: [ChromeOS]
* OS version: [78.0.3904.92]
* Browser name: [Chrome]
* Browser version: [78.0.3904.92]
* Extension version: [2.40]

After clearing with the extension, sites which have 'cache storage' such as cnet.com, walgreens.com, zdnet.com, wunderground.com remain - these are not sites with cookies saved either.

The only options I have not checked are cookies and passwords.

**Comment by dessant** [comment] 2019-11-11 17:22
How do you check what data remains after clearing?

**Comment by wiredrunner** [comment] 2019-11-11 17:29
chrome://settings/siteData

**Comment by dessant** [comment] 2019-11-15 02:31
I can't reproduce the issue, the cache is cleared when selected. cnet.com definitely saves a bunch of cookies, maybe that's what you confused with the cache.

**Comment by wiredrunner** [comment] 2019-11-15 02:41
It literally says "Cache Storage" so its pretty difficult to confuse that with 'cookie'.

The first image is chrome://settings/siteData prior to running 'clear browsing data' and the second is after running it.  Cookies are regularly swept by 'cookie auto delete' and on weatherunderground blocked altogether.  

Its not a huge issue just wanted to know if there was a way to avoid doing this manually.

![Screenshot 2019-11-14 at 9 34 26 PM](https://user-images.githubusercontent.com/25047709/68912739-13786e00-0727-11ea-8ca5-be6c329d6e82.png)
![Screenshot 2019-11-14 at 9 37 09 PM](https://user-images.githubusercontent.com/25047709/68912744-170bf500-0727-11ea-80c7-1f0ee612c0df.png)

**Comment by dessant** [comment] 2019-11-15 02:41
I've mixed things up, you're right, now I see the data that remains, even if all the data types are selected.

This is caused by a feature introduced in Chrome 72,  `cacheStorage` can be cleared separately, so it is no longer cleared with the browser cache.

https://developer.chrome.com/extensions/browsingData

**Comment by wiredrunner** [comment] 2019-11-15 02:45
Thanks.

**Comment by dessant** [comment] 2019-11-15 02:45
It's a problem because that storage can be used for tracking across browser sessions. Chrome should have continued to clear both types of cache for backward compatibility, even if they've introduced more granular control, or at least notify the developers of extensions with use the browsingData API.

**Comment by dessant** [comment] 2019-11-15 20:09
Fixed in https://github.com/dessant/clear-browsing-data/commit/c102d6cabf684fa9d7526a1616dcfe74721739f3.

@wiredrunner, thanks for taking the time to report and update the bug report, the new version will be published now.

**Closed by dessant** 2019-11-15 20:09 UTC
